### ISSUE TITLE
[Feature]: Inclusion of logo for  Cansat Ground Station project

### ISSUE THREAD

**Issue by swetha5157** [Gagan-Space/Cansat-Ground-Station#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

* The website currently lacks a logo
* Logo is essential in identifying websites and essential for unique identity

### Use Case

Adding logo make Cansat Ground statkon website more popular as picture speak more than words.

### Benefits

* This would bring unique identity to Cansat Ground Station website
* Kindly assign to me @swetha5157  under GSSoC'24.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by Witty-Wizard** [comment]
Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by swetha5157** [comment]
Kindly assign this issue to me @swetha5157

**Comment by swetha5157** [comment]
Since logo is present already, this issue could not be resolved.
Hence closing this issue.

**Comment by swetha5157** [comment]
Hence closing this issue
