### ISSUE TITLE
[Feature]: Add an impressive toggle button

### ISSUE THREAD

**Issue by AkhilaSunesh** [Gagan-Space/Cansat-Ground-Station#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Proposed  design
![image](https://github.com/Gagan-Space/Cansat-Ground-Station/assets/140897461/5ad56c07-fce9-49b7-952b-60f29bc98d9b)

### Use Case

Dark/Light mode

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by Witty-Wizard** [comment]
Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.
