### ISSUE TITLE
[Feature]: Login Page

### ISSUE THREAD

**Issue by Ojas-Arora** [Gagan-Space/Cansat-Ground-Station#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will add Login/Signup page . Kindly assign this issue to me @w

### Use Case

THis will add a new feature to the project.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by Witty-Wizard** [comment]
Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.
