### ISSUE TITLE
[Feature]: Add social media Icons in footer and include the links respectively

### ISSUE THREAD

**Issue by poseidonsanket** [Gagan-Space/Cansat-Ground-Station#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add social media Icons in footer and include the links respectively from the

### Use Case

Improves UI/UX

### Add ScreenShots

![Capture](https://github.com/Gagan-Space/Cansat-Ground-Station/assets/112609618/3c99accc-d059-4231-9dfb-8ed6aace5168)

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by poseidonsanket** [comment]
@Witty-Wizard please assign me this issue under gssoc

**Comment by bhaskar-2024** [comment]
please assign me this issue under gssoc
