### ISSUE TITLE
[Feature]: new footer design this footer very small and look dull

### ISSUE THREAD

**Issue by ayushpatel1248** [Gagan-Space/Cansat-Ground-Station#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

ill create the new footer which is also simple but more beautiful which conatain the links of all social media handle and also it will contain the ask question form , and also it will be bigger 

### Use Case

good user interface and experience 

### Benefits

this will attract the users

### Add ScreenShots

<img width="1439" alt="Screenshot 2024-06-13 at 4 27 55 PM" src="https://github.com/Gagan-Space/Cansat-Ground-Station/assets/127100604/0246662c-3cae-4206-9a20-8b63364a4f25">
![image](https://github.com/Gagan-Space/Cansat-Ground-Station/assets/127100604/0ab55d46-5427-4b81-838b-fd0a0cb7e80c)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by jayanththalla** [comment]
please assign me@pa
