### ISSUE TITLE
Add Time stamp

### ISSUE THREAD

**Issue by Witty-Wizard** [Gagan-Space/Cansat-Ground-Station#15]
# Time Stamp
Add time stamp for data plotting

## Implementation
- Add a time stamp to the csv file so that the graph can be plotted with respect to that.
- Start recording the time when the mission starts, refer #17

**Comment by Witty-Wizard** [comment]
#17, has been fixed in https://github.com/Gagan-Space/Cansat-Ground-Station/commit/7101244fe4710d9eb93768b900df2246f4c8fbdf

**Comment by TheSoumilArora** [comment]
#31
