### ISSUE TITLE
Manual Override Button

### ISSUE THREAD

**Issue by TheSoumilArora** [Gagan-Space/Cansat-Ground-Station#26]
**Problem**
There can be a situation where the auto deployment of parachute and heat shield may fail, or if the decent rate of the CANSAT is too high.

**Solution**
We want a manual override button that we can either manually trigger if we observe anything unusual, or it prompts us as well in case of a too high decent rate.
The override button works essentially by sending a command to open the parachute.

**Comment by Witty-Wizard** [comment]
This button will have to send data through web serial to the CANSAT to deploy the parachute.
For that #29 needs to be solved first

**Comment by DHRUVKHANDELWAL00** [comment]
Hey @Witty-Wizard Can i work on this under GSSOC?

**Comment by Witty-Wizard** [comment]
Hi, @DHRUVKHANDELWAL00  , I have assigned you this issue, please feel free to ask questions regarding the functionality of the project.

Also i would like you to share your thoughts process here in the comments

What is your understanding of the project
How are you thinking of going about it

**Comment by Witty-Wizard** [comment]
@LakshmiSowmya04 ,
I want to add a button that says deploy parachute. and when I press it, it should send data using web serial, for that check the serial.js file
