### ISSUE TITLE
Add maps for position tracking

### ISSUE THREAD

**Issue by TheSoumilArora** [Gagan-Space/Cansat-Ground-Station#28]
**Feature request**
We have the GPS coordinates via telemetry (https://github.com/Gagan-Space/Cansat-Ground-Station/issues/6). We wish to view the position of the CANSAT in real-time on maps

**Proposed solution**
Something like this can be made in a box
![pubnub_javascript_mapmarker](https://github.com/Gagan-Space/Cansat-Ground-Station/assets/92255142/2c5a945c-5f4d-4cf7-8bd1-3297487e2d12)

**Comment by aryapandeyy22** [comment]
i want to work on this issue under gssoc'24

**Comment by Witty-Wizard** [comment]
> i want to work on this issue under gssoc'24

Hi @aryapandeyy22, I have assigned you the issue to work on, please feel free to ask questions.
