### ISSUE TITLE
Serial Data Write

### ISSUE THREAD

**Issue by Witty-Wizard** [Gagan-Space/Cansat-Ground-Station#29]
**Problem Description**
Currently, our JavaScript application supports reading data from web serial but lacks the capability to send data over web serial. This limitation prevents us from fully utilizing the potential of web serial communication in our application.

**Solution**
Implement functionality in our JavaScript application to enable sending data over web serial. This would involve creating a feature that allows users to transmit data from the application to connected serial devices via the web serial API.

**Alternatives Considered**

1. Third-Party Libraries: Explore existing third-party libraries or frameworks that provide support for sending data over web serial. Evaluate the feasibility and compatibility of integrating such libraries into our application.
2. Custom Implementation: Consider developing a custom solution within our application to facilitate data transmission via web serial. This approach may require in-depth knowledge of the web serial API and JavaScript programming.

**Comment by masterboy376** [comment]
Hello @witty-wizard, I would like to work on this under GSSOC 2024.

**Comment by Witty-Wizard** [comment]
Hi, @masterboy376  , I have assigned you this issue, please feel free to ask questions regarding the functionality of the project.

Also i would like you to share your thoughts process here in the comments

What is your understanding of the project
How are you thinking of going about it
