### ISSUE TITLE
Add comments to the code

### ISSUE THREAD

**Issue by TheSoumilArora** [Gagan-Space/Cansat-Ground-Station#30]
**Description:**
The current version of the code lacks sufficient comments, making it challenging for developers to understand its functionality and implementation details.

**Proposed Solution:**

- Understanding the Code: Before adding comments, it's essential to thoroughly understand the codebase. Take time to analyze each block of code, understand its purpose, inputs, outputs, and any dependencies it relies on.
- Write Comments: Once you have a clear understanding of the code, start writing comments. Comments should be added next to each significant block of code, explaining its purpose, logic, and any relevant information that might help future developers comprehend it more easily.

**How it Helps:**

- Improved Code Comprehension: By adding comments, we enhance the code's readability and maintainability. Developers, including both current and future team members, can quickly grasp the code's functionality and make necessary modifications without extensive reverse engineering.
- Facilitates Collaboration: Clear comments promote collaboration among team members. When the codebase is well-documented, developers can collaborate more effectively, share insights, and provide constructive feedback, leading to better overall project outcomes.

**Comment by Digaa2710** [comment]
I would love to do this by adding comment section to the project by providing following features 
-Outstanding UI
-Stores replies using backend 
-Display replies 
-Reply functionality through likes and comments

**Comment by Witty-Wizard** [comment]
> I would love to do this by adding comment section to the project by providing following features -Outstanding UI -Stores replies using backend -Display replies -Reply functionality through likes and comments Plz assign me this issue under GSSoC'24

I think you misunderstood, by adding comments it meant adding comments to the code.

**Comment by Kk015** [comment]
Kindly assign this work to me under Gssoc24

**Comment by Witty-Wizard** [comment]
Hi, @Kk015 , I have assigned you this issue, please feel free to ask questions regarding the functionality of the project.

**Comment by Kk015** [comment]
Hi @Witty-Wizard ,

Thank you for assigning me the issue. I will do my best to resolve it efficiently and effectively. 

Based on my understanding, the project is built with React JS and Three JS and runs on a Vite server. Its primary objective is to display live data from the satellite and to export data in CSV form.

Regarding my approach, I plan to start by analyzing the codebase and identifying the relevant modules and functions.

Please let me know if you have any specific requirements or suggestions for me to consider while working on this issue. I am looking forward to resolving this issue in a timely and efficient manner

**Comment by Witty-Wizard** [comment]
> Hi @Witty-Wizard ,
> 
> 
> 
> Thank you for assigning me the issue. I will do my best to resolve it efficiently and effectively. 
> 
> 
> 
> Based on my understanding, the project is built with React JS and Three JS and runs on a Vite server. Its primary objective is to display live data from the satellite and to export data in CSV form.
> 
> 
> 
> Regarding my approach, I plan to start by analyzing the codebase and identifying the relevant modules and functions.
> 
> 
> 
> Please let me know if you have any specific requirements or suggestions for me to consider while working on this issue. I am looking forward to resolving this issue in a timely and efficient manner

It also uses redux for data transfer between components, there are also some more tools that have been used you will find them as you go through the code.

Best of luck?! 🚀

**Comment by Kk015** [comment]
![comment](https://github.com/Gagan-Space/Cansat-Ground-Station/assets/89037807/d1be45f2-3efc-4ea2-a65b-8b07ed24fc6b)
Should I reduce the number of comments or increase the explanation in each comment?

**Comment by Witty-Wizard** [comment]
> ![comment](https://github.com/Gagan-Space/Cansat-Ground-Station/assets/89037807/d1be45f2-3efc-4ea2-a65b-8b07ed24fc6b)
> 
> Should I reduce the number of comments or increase the explanation in each comment?

Add comments that you think explains the code best as per you.

You can also make a multiline comment like a paragraph explaining the component.

**Comment by Witty-Wizard** [comment]
> ![comment](https://github.com/Gagan-Space/Cansat-Ground-Station/assets/89037807/d1be45f2-3efc-4ea2-a65b-8b07ed24fc6b)
> 
> Should I reduce the number of comments or increase the explanation in each comment?

Add comments that you think explains the code best as per you.

You can also make a multiline comment like a paragraph explaining the component.

**Comment by Kk015** [comment]
Kindly check the pull request

**Comment by Kk015** [comment]
Kindly see the latest pr
