### ISSUE TITLE
Add Time stamp to the .csv file

### ISSUE THREAD

**Issue by TheSoumilArora** [Gagan-Space/Cansat-Ground-Station#31]
**Issue**
A time stamp needs to be added to the .csv file for plotting the data.

**Implementation**
- Add a time stamp to the csv file so that the graph can be plotted with respect to that.
- Start recording the time when the mission starts, refer https://github.com/Gagan-Space/Cansat-Ground-Station/issues/17

**Comment by nawarajshah** [comment]
@Witty-Wizard  I would like to work on this can you assign this to me?

**Comment by Witty-Wizard** [comment]
Hi, @nawarajshah, I have assigned you this issue, please feel free to ask questions regarding the functionality of the project.

Also i would like you to share your thoughts process here in the comments

- What is your understanding of the project
- How are you thinking of going about it

**Comment by Witty-Wizard** [comment]
@LakshmiSowmya04 , Hi!,
So currently in the app i am creating a csv file that stores the data, I want to plot that data later against time but since there is no time stamp in the csv I can not plot the data.

So I want you to add a time stamp to the csv, from the point the launch button is pressed

**Comment by Witty-Wizard** [comment]
Yes sure!!
