### ISSUE TITLE
Data analysis page

### ISSUE THREAD

**Issue by Witty-Wizard** [Gagan-Space/Cansat-Ground-Station#33]
**Description:**
To enrich the data analysis capabilities of the new data analysis page created using React Router, we propose implementing functionality to load CSV (Comma-Separated Values) data and visualize it on a graph. This feature will enable users to upload CSV files containing data sets and dynamically generate corresponding graphs for visual analysis.

#32, check this issue first 

**Proposed Solution:**

- CSV Data Loading: Develop functionality to allow users to upload CSV files directly from their devices or provide a URL to fetch CSV data from external sources. Utilize appropriate libraries or APIs to parse the CSV data and extract relevant information for visualization.
- Graph Visualization: Implement graph visualization capabilities to represent the loaded CSV data in a meaningful and intuitive manner. Consider using popular charting libraries such as Chart.js, D3.js, or Plotly to generate various types of graphs, including line charts, bar charts, scatter plots, etc. I would suggest using D3.js.

**Comment by AdityaNik** [comment]
can i work on this issue?

**Comment by Witty-Wizard** [comment]
> can i work on this issue?

Sure @AdityaNik , You can work on this issue but before that you have to make a new page using react router, that should load when analyse button is pressed. for that you should first work on #32 . Should I assign you that issue?

**Comment by AdityaNik** [comment]
ok sure!

**Comment by Witty-Wizard** [comment]
Can you comment on #32 , then i can assign you that issue aswell

**Comment by AdityaNik** [comment]
i need to add a seperate route for analysis page. can i go with 'react-router-dom'

**Comment by Witty-Wizard** [comment]
> @Witty-Wizard i need to add a seperate route for analysis page. can i go with 'react-router-dom'?

Yes sure!!

**Comment by AdityaNik** [comment]
@Witty-Wizard what parameters do i need to take for x and y axis of graph?

**Comment by Witty-Wizard** [comment]
For y axis take time and for x axis we will be plotting the incoming data, check project readme for that

**Comment by AdityaNik** [comment]
@Witty-Wizard can you please elaborate a bit because it's bit confusing in readme (PS: sorry, exams were going on that's why less attention on this)

**Comment by Witty-Wizard** [comment]
Have you created a new page using react router?

**Comment by AdityaNik** [comment]
yess, that part is done

**Comment by Witty-Wizard** [comment]
Great!

https://youtu.be/J8-JUlw993A?feature=shared, please see this i want to plot graphs like this

**Comment by AdityaNik** [comment]
ok👍

**Comment by AdityaNik** [comment]
i think #31 is not solved yet, for the time stamp purpose?

**Comment by Aryaman9999** [comment]
Sure, go ahead.

**Comment by Witty-Wizard** [comment]
@AdityaNik , Can you create a Story for this component using story book, and create a new issue for it so that you get points
