### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by Pranjalll01** [Gagan-Space/Cansat-Ground-Station#36]
Hey 
Pranjal here Contributor @GSSOC'24
repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

could you assign this to me ?

**Comment by Witty-Wizard** [comment]
Hi, @Pranjalll01 , I have assigned you this issue, please feel free to ask questions regarding the functionality of the project.

Also i would like you to share your thoughts process here in the comments

- What is your understanding of the project
- How are you thinking of going about it

**Comment by KavyaBS123** [comment]
@Witty-Wizard can you please assign this issue to me I would like to work on it.

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by n14rishitha** [comment]
Hi @Witty-Wizard 
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3

**Comment by n14rishitha** [comment]
@Witty-Wizard 
Thank you for giving me this chance.
