### ISSUE TITLE
[Bug] : Responsive issue

### ISSUE THREAD

**Issue by sivaprasath2004** [Gagan-Space/Cansat-Ground-Station#37]
**Describe the bug**
In this Page not proper Resposive mode.

**To Reproduce**
1. see in our project
2. click on the inspect 
3. go to the mobile site mode 
4. see the responsive error

**Expected behavior**
The container outside the screen will overflow.

**Screenshots**

![Screenshot from 2024-05-11 07-24-51](https://github.com/Gagan-Space/Cansat-Ground-Station/assets/121082414/be80347d-8294-4b3a-9b89-c1a7963d7548)

[Screencast from 2024-05-11 07-30-17.webm](https://github.com/Gagan-Space/Cansat-Ground-Station/assets/121082414/9594d1ce-67fc-4fbb-ae51-c019753d0451)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : chrome

**Smartphone (please complete the following information):**
 - Device: Realme
 - OS: Android 12
 - Browser : chrome

**Comment by Witty-Wizard** [comment]
Hi!, @sivaprasath2004 , thanks for pointing out this bug, but This project is made to run on an desktop enviornment and in the coming future I plan to shift from web application to native application by using Electron to build the native application. Till then this issue will serve as a place for discussion for its development.

I would also love to see if this app could be made to run on mobile devices, that support serial communication using USB.

**Comment by sivaprasath2004** [comment]
Hi!, @Witty-Wizard Yes ok,at least i will try to make proper responsive site.please assign me.

**Comment by sivaprasath2004** [comment]
@Witty-Wizard please add the `level` label your missing for me....

**Comment by KavyaBS123** [comment]
@sivaprasath2004 can you please assign this issue to me
