### ISSUE TITLE
Create Documentation using MkDocs

### ISSUE THREAD

**Issue by Witty-Wizard** [Gagan-Space/Cansat-Ground-Station#38]
# Description
We currently lack proper documentation for our project, which is crucial for onboarding new contributors and users. To address this, I propose using MkDocs, a popular static site generator geared towards creating project documentation.

Proposed Solution:

1. Set up MkDocs in our project repository.
2. Organize existing project information into Markdown files compatible with MkDocs.
3. Write comprehensive documentation covering installation instructions, usage guidelines, API references (if applicable), and contribution guidelines.
4. Integrate MkDocs with GitHub Pages for easy hosting and access.

**Comment by Abhishek-Sood** [comment]
hello, i wanted to ask that for writing a documentation we need to know each and everything about the project where can i find all the material like a readme or something because the current readme do not provide any details of the project.

**Comment by Witty-Wizard** [comment]
Hi!, @Abhishek-Sood , we currently do not have any readme for this project. That was the objective of this issue.
I can help you with this, we can connect on discord.

**Comment by Abhishek-Sood** [comment]
yes sir id love to work on this
