### ISSUE TITLE
Transition Web App from Vite to Electron

### ISSUE THREAD

**Issue by Witty-Wizard** [Gagan-Space/Cansat-Ground-Station#39]
# Objective
Transition our web application from Vite to Electron to enhance its usability and provide a more native experience across different platforms.

# Current State:
Our web application is currently built using Vite, which offers fast builds and a modern development experience for web projects. However, I would like to transistion to electron for a more native experience. The vite build process is only for initial testing and we are eventually going to package and distribute this app for native enviornment.

**Comment by NaunihalSingh40** [comment]
Hi @Witty-Wizard Naunihal Singh this side from Gssoc, transition of web app to an electron desktop is a great task to do.
I request you to assign this task to me. 

I will be glad to have this opportunity!

**Comment by NaunihalSingh40** [comment]
I have completed the task successfully by adding dependencies and installing electron in the pre-existing(provided) vite app 

https://github.com/Gagan-Space/Cansat-Ground-Station/assets/109708929/f8e7e8f1-da87-439d-aa91-e4a63f39265a

**Comment by NaunihalSingh40** [comment]
@Witty-Wizard please check and instruct further

**Comment by Witty-Wizard** [comment]
Thats great to see!!!

Now as i see the connect functionality has stopped working,
So how about i merge this pr to another branch and the create another issue where you can fix this bug?

**Comment by Witty-Wizard** [comment]
@NaunihalSingh40 , I have created a new branch , https://github.com/Gagan-Space/Cansat-Ground-Station/tree/electron-transistion, Create a PR to this branch and we will start from there

**Comment by NaunihalSingh40** [comment]
I have forked and cloned the forked repository on my local device, the connect functionality I guess was not working at web application also.
Can you please advice about the details of connect functionality if provided anywhere, so that i may work over it.

And please mention your linkdn profile so that i may share my workings with gssoc over it.

**Comment by Witty-Wizard** [comment]
> I have forked and cloned the forked repository on my local device, the connect functionality I guess was not working at web application also. Can you please advice about the details of connect functionality if provided anywhere, so that i may work over it.
> 
> And please mention your linkdn profile so that i may share my workings with gssoc over it.

I have checked the connection functionality works on Edge and Chrome, please tell which browser are you using?
For testing this on your system you have to install a software to emulate a hardware device.
- com0com or
- Virtual Serial port tool
Then you can try the connection functionality, also I think that you have to enable serial functionality in electron.

reference:
- https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API#:~:text=The%20Web%20Serial%20API%20provides,that%20emulate%20a%20serial%20port.
- https://wicg.github.io/serial/
- https://serialport.io/docs/guide-electron
![Connected](https://github.com/Gagan-Space/Cansat-Ground-Station/assets/48916902/0eb7f989-c794-4e79-b267-378be8160a25)
![Connect option](https://github.com/Gagan-Space/Cansat-Ground-Station/assets/48916902/e77cfa9b-bfd0-4543-934b-57ac3c9551ee)

**Comment by NaunihalSingh40** [comment]
i have tried working over it and still working on it, but for connecting the Virtual serial port tool it connects with local software and files which show same errors again when code is re-cloned

**Comment by Witty-Wizard** [comment]
> i have tried working over it and still working on it, but for connecting the Virtual serial port tool it connects with local software and files which show same errors again when code is re-cloned

Can you share the error?
and yes it is supposed to connect with local software

**Comment by Witty-Wizard** [comment]
@NaunihalSingh40 , Can you create a PR so that i can check it on my own system.

**Comment by Witty-Wizard** [comment]
So you need to create a fork of the repo and then push on that,
After that create a PR to merge that into the main repo
