### ISSUE TITLE
Landing page frontend ui

### ISSUE THREAD

**Issue by Rohitha-pudu** [Gagan-Space/Cansat-Ground-Station#43]
### It lacks a landing page /home page 
I will work on this issue .please assign this to me

**Comment by Rohitha-pudu** [comment]
can i use tailwind

**Comment by Witty-Wizard** [comment]
> can i use tailwind @Witty-Wizard

Hi!, @Rohitha-pudu , I am trying to avoid the use of tailwind, also what kind of a landing page are you thinking of making? then we can discuss further from here

**Comment by Rohitha-pudu** [comment]
![image](https://github.com/Gagan-Space/Cansat-Ground-Station/assets/116823590/9ce4fb1b-18de-4d89-a31c-360525d11f3b)
working on this,is it okay

**Comment by Witty-Wizard** [comment]
> ![image](https://github.com/Gagan-Space/Cansat-Ground-Station/assets/116823590/9ce4fb1b-18de-4d89-a31c-360525d11f3b)
> 
> working on this,is it okay @Witty-Wizard 

Looks great,I was thinking you could make this into a loading screen or kind of a splash screen that loads before the app loads

**Comment by Rohitha-pudu** [comment]
ha i was thinking the same,like a home screen ,using the button user navigates to data page

**Comment by Witty-Wizard** [comment]
Cool look amazing, for buttons font we are using googles material design so you can use material UI library which is based on google material UI design, and Best of Luck!!!
