### ISSUE TITLE
Automated Greeting Workflow

### ISSUE THREAD

**Issue by sanmarg** [Gagan-Space/Cansat-Ground-Station#45]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet(using Github Bots) users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me

**Comment by Witty-Wizard** [comment]
Hi, I was almost about to create this issue.
1. How are you going to implement this?
2. Can you create an git action that automatically assigns reviewer to a PR?

**Comment by sanmarg** [comment]
I have implemented this but I am not sure how to automatically assigns reviewer to a PR... Could you please let me research on this and make another issue for this

**Comment by Witty-Wizard** [comment]
> I have implemented this but I am not sure how to automatically assigns reviewer to a PR... Could you please let me research on this and make another issue for this

Auto assign pr has been done , you can create a pr for the welcome message
