### ISSUE TITLE
Migrate from Web Serial to Node Serial Port in Electron

### ISSUE THREAD

**Issue by Witty-Wizard** [Gagan-Space/Cansat-Ground-Station#55]
## Description
We currently use Web Serial for serial communication in our Electron application. However, due to limitations or requirements, we need to migrate to using Node Serial Port. This issue tracks the migration process.

## Context
Web Serial API provides a browser-based approach for communicating with serial devices, which is suitable for web applications. However, in Electron, we have access to Node.js APIs, including the serialport module, which offers more flexibility and control over serial communication.

## Reasoning
There could be several reasons for migrating to Node Serial Port:

- Access to Node.js Ecosystem: Utilizing Node.js APIs allows us to leverage the entire Node.js ecosystem, including the serialport module and its extensive features.
- Platform Compatibility: Node Serial Port may offer better compatibility with various platforms compared to Web Serial, especially in an Electron environment.
- Advanced Features: Node Serial Port provides advanced features and configurations for serial communication, which may be required for our application.

## Proposed Steps
- [ ] Replace Web Serial Calls: Identify and replace all instances of Web Serial API calls in the codebase with equivalent functionality using the serialport module.
- [ ] Update Dependencies: Ensure that the serialport module is installed as a dependency in the project.
- [ ] Refactor Serial Communication Logic: Refactor the serial communication logic to work with the serialport module, considering differences in API and behavior.
- [ ] Testing: Test the migration thoroughly to ensure proper functionality and compatibility across platforms.
- [ ] Documentation: Update relevant documentation, including README and code comments, to reflect the changes and provide guidance on using Node Serial Port.

## Related Issues:
First implement Electron as in #39

**Comment by exploring-solver** [comment]
Please assign this to me under gssoc.
