### ISSUE TITLE
Add login /signup page on homepage

### ISSUE THREAD

**Issue by kavitameena108** [Gagan-Space/Cansat-Ground-Station#56]
create a login/signup page 
    1. Build the login functionality,including form validation and error handling .
    2. Implemention the user signup feature,allowing  new users to register.

**Comment by Witty-Wizard** [comment]
Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by kavitameena108** [comment]
@Witty-Wizard  please assign  me this issue under GSSoc'24 and add label.

**Comment by Witty-Wizard** [comment]
@kavitameena108, Sorry but this Application does not need a login page, this is a local application.
