### ISSUE TITLE
Typescript migration bug

### ISSUE THREAD

**Issue by Aryaman9999** [Gagan-Space/Cansat-Ground-Station#62]
**Describe the bug**
All redux and storybook files have not been migrated to TS.

**Expected behavior**
It should build without error.

**Additional context**
Error: tsconfig.json(10,25): error TS6046: Argument for '--moduleResolution' option must be: 'node', 'classic', 'node16', 'nodenext'.
Error: tsconfig.json(11,5): error TS5023: Unknown compiler option 'allowImportingTsExtensions'.
Error: tsconfig.json(12,5): error TS5070: Option '--resolveJsonModule' cannot be specified without 'node' module resolution strategy.

**Comment by Witty-Wizard** [comment]
Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by 2003sidd** [comment]
hey @Witty-Wizard ,I have prior knowledge of react and typescript so assign this issue to migrate all redux and storybook into typescript

**Comment by Witty-Wizard** [comment]
@2003sidd , I have assigned you this issue 
please create a PR on https://github.com/Gagan-Space/Cansat-Ground-Station/tree/typescript-migration branch

**Comment by 2003sidd** [comment]
ok @Witty-Wizard

**Comment by Aryaman9999** [comment]
@2003sidd any update?
