### ISSUE TITLE
Redesign the UI/UX

### ISSUE THREAD

**Issue by Witty-Wizard** [Gagan-Space/Cansat-Ground-Station#63]
The current user interface and user experience of our ground station software have been identified as areas needing improvement. A more intuitive and visually appealing design will enhance usability, reduce operator errors, and provide a better overall experience for users.

## Goals
Improve the visual design of the ground station interface.
Enhance user experience by making the interface more intuitive and user-friendly.
Ensure the redesign supports all existing functionalities without introducing new bugs.
Requirements
## Visual Design:

Update the color scheme to be more modern and visually appealing.
Redesign icons and buttons to be more intuitive.
Improve the layout for better readability and ease of use.
Ensure that the interface is responsive and works well on various screen sizes.
## Simplify the navigation structure.
Improve feedback mechanisms (e.g., success/failure notifications, loading indicators).
Enhance data visualization (e.g., graphs, charts) to provide clear and concise information.
Functionality:

## Ensure all current functionalities are retained.
Test the redesigned interface thoroughly to avoid any new bugs or issues.
Provide clear documentation on the new design for future reference and user onboarding.

**Comment by kavitameena108** [comment]
I want to work on this issue please assign me @Witty-Wizard

**Comment by Shweta-281** [comment]
I want to work on this issue please assign me

**Comment by kavitameena108** [comment]
I'm already working on it
