### ISSUE TITLE
🪲[Bug]: there has no icon in the website

### ISSUE THREAD

**Issue by AnitSarkar123** [Gagan-Space/Cansat-Ground-Station#68]
**Describe the bug**
favion is not present

please assign me under Gssoc24

**Comment by Witty-Wizard** [comment]
Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by Witty-Wizard** [comment]
It is being worked on in #50
